// Datos de testimonios. Vive en un archivo plano (sin "use client") para
// poder importarse tanto desde componentes cliente (testimonials.tsx,
// social-proof-strip.tsx) como desde Server Components (layout.tsx, para
// el schema.org JSON-LD) sin que Next.js lo convierta en una referencia
// de cliente opaca.

export interface Testimonial {
  id: number
  label: string
  role: string
  server: string
  mcUsername: string
  text: string
}

export const allTestimonials: Testimonial[] = [
  { id:  1, label:'ヽHoney﹒.',    role:'Owner',    server:'ChillMon',    mcUsername:'Grian',           text:'Muy buen trabajo, rápido y eficaz, además de precios accesibles @Dark gracias por el trabajo hecho' },
  { id:  2, label:'ⁿᵏ𝐕𝐚𝐥𝐞𝐧 ⚝.',       role:'Owner',    server:'EnigmaWorld',      mcUsername:'Mumbo',            text:'Exelente servicio, muy atento siempre, le compre una config de playerkits le hable y me la cambio sin problemas, hoy le compre el servidor survival porque me parecio exelente y muy amable siempre, totalmente recomendado ' },
  { id:  3, label:'jotkeiz.',     role:'Owner',    server:'EclipseCraf',   mcUsername:'iskall85',      text:'Excelente trabajo en el servidor de Minecraft y la tienda Tebex Fue muy paciente durante todo el proceso, trabajó de manera rápida y eficiente, y siempre estuvo dispuesto a ayudar ante cualquier duda' },
  { id:  4, label:'Enziuu',     role:'Owner',  server:'Astralis MC',   mcUsername:'Xisumavoid',           text:'Excelente trabajo el que me realizó,  le pedí una tienda tebex completa y me la hizo tal y como se la pedí,  le doy un 10/10 ,es muy paciente la verdad y dedicado a su trabajo' },
  { id:  5, label:'★彡 TITAN 彡★',     role:'Owner',    server:'Beetlejuice',   mcUsername:'ZombieCleo',     text:'Excelente servicio que hizo a mi tienda tebex no sería la primera ni la última vez que voy a contratar sus excelentes servicios' },
  { id:  6, label:'JLuis_',     role:'Owner',      server:'MineLatin',    mcUsername:'Docm77',       text:'Un excelente servicio. La atención al cliente, la disponibilidad y el tiempo de entrega superaron mis expectativas. Solo tenía ideas muy vagas para mi servidor y pensé que sería difícil que las entendiera, pero su trabajo me sorprendió. Si tienen la oportunidad, no duden en contratar sus servicios' },
  { id:  7, label:'Lears_One',   role:'Owner',    server:'Pixel Of God', mcUsername:'Ethoslab',          text:'El trabajo y la atencion de @Dark un 10/10  muy buen servicio y  trabajo, estoy esperando tener muchas mas oportunidades de trabajar con usted , es todo lo que se  solicita en una persona con el conocimiento y la capacidad de completar todas las tareas 100%' },
  { id:  8, label:'LeoMendoza',     role:'Owner', server:'Tierra arcana',      mcUsername:'FalseSymmetry',      text:'La experiencia con @DARK_NESS fue excelente, la atencion a lo que uno requiere y le solicita, es muy buena, el tiempo igual es muy bueno, te resuelve todas tus dudas , si tienes algun problema de igual manera te resuelve y te ayuda hasta que termina el trabajo ' },
  { id:  9, label:'Pirzi.',      role:'Owner',    server:'ArgWorld',    mcUsername:'Rendog', text:'Sinceramente si es buen servicio, mucha ayuda y mas que yo no se hacer nada xd te re agradezco @Dark ' },
  { id: 10, label:'SrBos',     role:'Owner',    server:'NexusMC',    mcUsername:'ImpulseSV',        text:'Muy buen servicio de @Dark le pedi configuracion de dungeons y minas customs y fue bastante atento a los detalles solicitados, servicio eficiente y sin complicaciones 10/10' },
  { id: 11, label:'YisusCm23.',    role:'Owner',  server:'SkyCraft',   mcUsername:'Cubfan135',      text:'Uffff gracias por el servicio Bro @Dark la verdad muy amable, paciente, la verdad 10/10 Le pedí una configuración completa de mi servidor a como es mi gusto y fue mejor de lo que esperaba. La verdad no me arrepiento de haber pedido sus servicios 🙏🏻' },
  { id: 12, label:'alesinho912',    role:'Owner',    server:'KittyCraft',    mcUsername:'Welsknight',  text:'Mi experiencia con el servicio de @Dark fue muy buena! le compré un servidor completo me ayudó a configurar y modificar paso a paso las cosas a mi gusto, estuvo a. disposición cada instante. El resultado supero todas mis expectativas, todo quedó de 10... Estoy seguro que voy a seguir necesitando de sus servicios! Super recomendado' },
  { id: 13, label:'xFrosedYT⚡',  role:'Owner',    server:'LuxorMC',  mcUsername:'WilburSoot',          text:'Compre el Servicio de tebex, no fue nada caro, la tienda quedo increíble, es un genio @Dark, super recomendado si tienen pensado comprar su servicio de tebex, o cualquier otro servicio o configuración. 10/10' },
  { id: 14, label:'Shinji21',    role:'Owner',    server:'GalaxyCraft',      mcUsername:'PearlescentMoon',      text:'Mi experiencia con este servicio fue excelente. @Dark  se encargó de crear y configurar mi servidor de Minecraft de manera muy profesional, cuidando cada detalle para que todo quedara funcionando correctamente desde el inicio. El tiempo de espera fue exactamente el estimado, Durante el proceso siempre hubo buena comunicación, resolviendo mis dudas de forma clara y rápida. El resultado final superó mis expectativas: un servidor estable, bien optimizado y listo para disfrutar sin complicaciones.' },
  { id: 15, label:'TorreRock',    role:'Owner',    server:'MagisCraft',  mcUsername:'Nihachu',          text:'Compre un servidor completo a @Dark  y todo perfecto configuración traducción de todos los plugins y un servicio la verdad de 10 me gustó mucho su trato y todo ' },
  { id: 16, label:'SirExhon❤🇲🇽🔥', role:'Owner',      server:'ImperialCraft',     mcUsername:'Hbomb94',            text:'Compre un Servidor con @Dark la configuracion es una perfeccion total, y la verdad fue en tiempo muy corto al realizar la compra la entrega fue casi inmediata y me sorprendió la calidad, sin duda quedo satisfecho con el producto que se me entrego, supero mis espectativas. Seguire adquiriendo sus servicios y productos por la profecionalidad y puntualidad del servicio.' },
  { id: 17, label:'! Strovo', role:'Owner',    server:'hytalebox',    mcUsername:'Skizzleman',        text:'Mande hacer las traducciones a @Dark de varios plugin, y la verdad fue en tiempo récord (eran complejas) y me sorprendió la calidad y el tiempo de entrega de todo, estoy seguro que estaré haciendo mas negocios ya que este tipo de trabajos es lo que he estado buscado, gente que  cumpla su palabra y que sea bueno en lo que hace.' },
  { id: 18, label:'DinoBossYT',     role:'Owner', server:'IronMC',       mcUsername:'Vikkstar123',         text:'Hola, como siempre intento ser sincero por más que a veces eso pueda ser un dolor para los configurados. En esta ocasión quiero reconocer a @DEMON, quien se comportó como un verdadero profesional. Su trabajo de traducción fue impecable: ordenado, limpio y perfectamente adaptado. Lo más destacable fue su capacidad de resolver los desafíos adicionales que le propuse, los cuales no eran sencillos, y aun así los completó en un tiempo corto y con una calidad sobresaliente. Recomiendo plenamente su servicio; demuestra compromiso, responsabilidad y un nivel de dedicación difícil de encontrar' },
  { id: 19, label:'𝐒𝐨𝐲𝐒𝐞𝐛𝐚𝐬𝐃𝐌𝐂.',     role:'Owner', server:'AtlasMC',       mcUsername:'BdoubleO100',         text:'He pedido un servidor y de manera instantánea, efectivamente se compromete y super chévere la profesionalidad de @Dark 10/10 el trabajo. Se los recomiendo ' },
  { id: 20, label:'Azkelaf',     role:'Owner', server:'LatinoCraft',       mcUsername:'VintageBeef',         text:'Una vez más he solicitado sus servicios y como siempre sigue siendo un persona profesional y dedicada a su oficio, sin duda alguna lo tendré como mi configurador de cabecera.' },
  { id: 21, label:'LEØ_404.',     role:'Owner', server:'EtheniumMC',       mcUsername:'Fundy',         text:'He solicitado varios servicios con ciertas especificaciones y me ha entregado trabajos 10/10 realmente un trabajo elegante, profesional totalmente entregado a su trabajo. Totalmente recomiendo sus servicios ' },
  { id: 22, label:'Dionisio',     role:'Owner', server:'Kweeverse',       mcUsername:'Jschlatt',         text:'Configuracion rapida, eficaz, profesional y estetica. Trato personalizado segun las necesidades del cliente y buenos precios. Lo volveria a contratar' },
  { id: 23, label:'ryback',       role:'Owner', server:'TempusGod',      mcUsername:'Dream',        text:'Aún estamos en el primer paso del proyecto, pero desde ya puedo decir que es un tipazo. Es muy comprensible, paciente y siempre está dispuesto a ayudar. Aunque no tenga todo el conocimiento técnico en cada detalle, se nota que pone bastante empeño en asesorarte bien y en buscar soluciones para que el servidor quede como quieres. Más allá de solo “configurar”, también te orienta, te da ideas y se involucra en el proyecto, lo cual vale bastante cuando estás empezando algo así. Eso genera confianza y hace que el proceso sea mucho más llevadero.🔥 Hasta ahora, muy buena experiencia y totalmente recomendado si buscas a alguien que te apoye y te acompañe en el proceso de crear tu servidor.🎉' },
  { id: 24, label:'JLuis_',       role:'Owner', server:'LIMP',           mcUsername:'Technoblade',          text:'Estoy muy contento con la configuración de mi servidor no tardo en terminar, puso lo que quería como también me aconsejo que cosas podrían mejorar 10/10' },
  { id: 25, label:'Shields',      role:'Owner', server:'Bot Discord',    mcUsername:'Tommyinnit',           text:'Muy profesional, muy rápido, no sabía ni como quería el diseño y me sorprendió recomendado, hace buenos discord y su bot es good' },
  { id: 26, label:'Leonar',       role:'Comprador BBB', server:'AlonsoTags Config', mcUsername:'Ranboo',    text:'Gran configuracion!! Muy profesional' },
  { id: 27, label:'Leonar',       role:'Comprador BBB', server:'Quests Config', mcUsername:'GeorgeNotFound', text:'Buena configuracion!! 100% recomendado' },
  { id: 28, label:'boraz6',       role:'Comprador BBB', server:'Quests Config', mcUsername:'Sapnap',        text:'muy buena config recomendable buen soporte' },
  { id: 29, label:'sh4ruk3',      role:'Comprador BBB', server:'Quests Config', mcUsername:'Quackity',      text:'Excelente config. Indicaciones detalladas para la instalación.' },
  { id: 30, label:'TrollxTroll',  role:'Comprador BBB', server:'Rankup + Kits Config', mcUsername:'Purpled', text:'La Verdad buena config de rank, Dark excellente persona, te ayuda siempre q lo necesites, tanto este como sus otros complementos valen totalmente la pena :).' },
  { id: 31, label:'TrollxTroll',  role:'Comprador BBB', server:'ProtectionStones Config', mcUsername:'Skeppy', text:'Muy buena, todo bien traducido y buenos colores.' },
  { id: 32, label:'xXSk473Xx',    role:'Owner', server:'GRX',            mcUsername:'BadBoyHalo',           text:'D4RK un excelente DEV hasta el momento me ha ayudado mucho en mi server, precios justos y su trabajo 10/10, lo que hizo en mi server configuración y añadido de Plugins al 100% también creo y configuró mi página web, el diseño fue 10/10. LO RECOMIENDO ABSOLUTAMENTE' },
  { id: 33, label:'SoyLuisitoRD', role:'Owner', server:'StoryWars',      mcUsername:'Antfrost',             text:'Quedé muy satisfecho con el trabajo de D4RK. La calidad de las configuraciones, los tiempos de entrega y el diseño superaron mis expectativas. Además, no solo se limita a realizar el servicio, sino que también aporta ideas y recomendaciones para mejorar el servidor, demostrando un gran profesionalismo y compromiso con el proyecto. Sin duda, lo recomiendo al 100%.' },
  { id: 34, label:'Zick',         role:'Owner', server:'StoryWars',      mcUsername:'Philza',               text:'D4RK es un excelente DEV. Hasta el momento me ha ayudado muchísimo con mi servidor, siempre ofreciendo precios justos y un trabajo de calidad. Se encargó de configurar y añadir plugins, dejando todo funcionando al 100%. Incluso me ayudó con varios problemas y configuraciones de mi VPS. Es una persona muy responsable, agradable y atenta. Su trabajo es 10/10 y lo recomiendo absolutamente.' },
  { id: 35, label:'𓆩 ziFrostid 𓆪', role:'Owner', server:'ٴٴ',           mcUsername:'Awesamdude',           text:'Me encanta la calidad de como trabaja y lo bien que se adapta según tu presupuesto con precios muy razonables. Además, corrige cualquier error de inmediato. Sin duda, totalmente recomendado.' },
]
